### PR TITLE
Only display a colour block if a colour is explicitly defined

### PR DESCRIPTION
**Pull request by joshsadam**
Hi Guys,

We have a lot of columns that are users do not want a colour block displayed for (e.g. comments).  What I am attempting to do here is to hide the block unless a colour is explicitly defined for it:

``` javascript
leaf.data[colName] = {
  colour:  'rgb(255, 109, 0)',
  //
 ...
};
```

no_block

### CODE REVIEW

**Comment by joshsadam** [comment]
@kabudahab can you take a look at this and let me know what you think.  It is a feature that is really requested around here.

**Comment by richardgoater** [comment]
Hi @joshsadam, Khalil is away on holiday and won't be back till 30th January. I'm a bit swamped atm so I don't know if I'll be able to look at it. Are you able to use/currently using your fork in production?

**Comment by joshsadam** [comment]
Thanks for the update @richardgoater.  If needed I can do that, but I can also just hold it until a subsequent release.

**Comment by joshsadam** [comment]
Guess this is not needed anymore

**Pull request closed without merging**
